port = "58080"
port = ${?port}
db-config {
 type = dynamo-db-config
 type = ${?DB_TYPE}
 endpoint = "http://localhost:8001"
 endpoint = ${?DB_ENDPOINT}
 key = "fakeMyKeyId"
 key = ${?KEY}
 secret = "fakeSecretAccessKey"
 secret = ${?SECRET}
 table = "PersonTable"
 table = ${?TABLE}
}
