job-name = "generator"
job-name = ${?JOB_NAME}
kafka-config {
 bootstrap-servers = "localhost:9092"
 bootstrap-servers = ${?BOOTSTRAP_SERVERS}
 output-topic = "raw-data"
 output-topic = ${?OUTPUT_TOPIC}
}
generate-per-sec = "1"
generate-per-sec = ${?GENERATE_PER_SECOND}
db-config {
 type=no-op-db-config
}
