// transformer conf
job-name = "transformer"
job-name = ${?JOB_NAME}
kafka-config {
 bootstrap-servers = "localhost:9092"
 bootstrap-servers = ${?BOOTSTRAP_SERVERS}
 input-topic = "raw-data"
 input-topic = ${?INPUT_TOPIC}
 output-topic = "transformed-data"
 output-topic = ${?OUTPUT_TOPIC}
}
db-config {
 type=no-op-db-config
}
