job-name = "writer"
job-name = ${?JOB_NAME}
kafka-config {
 bootstrap-servers = "kafka:9092"
 bootstrap-servers = ${?BOOTSTRAP_SERVERS}
 input-topic = "transformed-data"
 input-topic = ${?INPUT_TOPIC}
}
generate-per-sec = "1"
generate-per-sec = ${?GENERATE_PER_SECOND}

db-config {
 type = dynamo-db-config
 type = ${?DB_TYPE}
 endpoint = "http://localhost:8001"
 endpoint = ${?ENDPOINT}
 key = "fakeMyKeyId"
 key = ${?KEY}
 secret = "fakeSecretAccessKey"
 secret = ${?SECRET}
 table = "PersonTable"
 table = ${?TABLE}
}
